apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx2
      image: nginx:1.14.2
      ports:
        - containerPort: 80
    - name: apache
      image: httpd
      ports:
        - containerPort: 8080